name: python-app-project
on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: build image
      shell: bash
      run: sudo apt update